# natural stuff
coastline:
  Color: {Red: 0, Green: 15, Blue: 191}
  Characters: [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175]
desert:
  Color: {Red: 127, Green: 127, Blue: 31}
  Characters: [128, 129, 130]
forest:
  Color: {Red: 0, Green: 63, Blue: 0}
  Characters: [16, 17, 18, 19]
grass:
  Color: {Red: 31, Green: 159, Blue: 63}
  Characters: [179, 180, 181, 182, 183]
ice:
  Color: {Red: 239, Green: 239, Blue: 255}
  Characters: [177]
rock:
  Color: {Red: 95, Green: 95, Blue: 95}
  Characters: [192]
sea:
  Color: {Red: 0, Green: 15, Blue: 127}
  Characters: [208] #[131, 132, 133, 134, 135, 136, 137, 138]

# adjustable resources
human:
  Color: {Red: 255, Green: 127, Blue: 127}
  Characters: [64]
wood:
  Color: {Red: 63, Green: 191, Blue: 0}
  Characters: [35]
food:
  Color: {Red: 0, Green: 191, Blue: 63}
  Characters: [127]
culture:
  Color: {Red: 0, Green: 0, Blue: 127}
  Characters: [68]
visibility:
  Color: {Red: 0, Green: 0, Blue: 0}
  Characters: [32]

# activities and buildings:
settlement:
  Color: {Red: 255, Green: 255, Blue: 255}
  Characters: [1]
foraging:
  Color: {Red: 63, Green: 159, Blue: 127}
  Characters: [2]
logging:
  Color: {Red: 191, Green: 191, Blue: 191}
  Characters: [3]
wall:
  Color: {Red: 31, Green: 63, Blue: 15}
  Characters: [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159]
farm:
  Color: {Red: 63, Green: 255, Blue: 63}
  Characters: [6]
road:
  Color: {Red: 127, Green: 127, Blue: 127}
  Characters: [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159]
shaman:
  Color: {Red: 255, Green: 127, Blue: 127}
  Characters: [5]
orchard:
  Color: {Red: 127, Green: 255, Blue: 127}
  Characters: [4]
bulldozer:
  Color: {Red: 127, Green: 127, Blue: 127}
  Characters: [0]