- type: settlement
  ResourceLowerBoundConstraint: {}
  ResourceUpperBoundConstraint: {sea_depth: 0}
  cost: {human: 2, wood: 2}
  supply: {human: 1}
  demand: {food: 1}

- type: foraging
  ResourceLowerBoundConstraint: {}
  ResourceUpperBoundConstraint: {sea_depth: 0}
  cost: {}
  supply: {food: 1}
  demand: {human: 1}

- type: logging
  ResourceLowerBoundConstraint: {}
  ResourceUpperBoundConstraint: {sea_depth: 0}
  cost: {}
  supply: {wood: 1}
  demand: {human: 1}

- type: orchard
  ResourceLowerBoundConstraint: {}
  ResourceUpperBoundConstraint: {sea_depth: 0}
  cost: {human: 1}
  supply: {food: 2}
  demand: {human: 2}

- type: farm
  ResourceLowerBoundConstraint: {}
  ResourceUpperBoundConstraint: {sea_depth: 0}
  cost: {human: 1, wood: 1}
  supply: {food: 3}
  demand: {human: 3}

- type: road
  ResourceLowerBoundConstraint: {}
  ResourceUpperBoundConstraint: {sea_depth: 0}
  cost: {human: 1, stone: 1}
  supply: {}
  demand: {}

- type: wall
  ResourceLowerBoundConstraint: {}
  ResourceUpperBoundConstraint: {sea_depth: 0}
  cost: {human: 1, wood: 1}
  supply: {}
  demand: {}

- type: shaman
  ResourceLowerBoundConstraint: {}
  ResourceUpperBoundConstraint: {sea_depth: 0}
  cost: {human: 5, wood: 1}
  supply: {}
  demand: {}

- type: bulldozer

#- type: well
#  ResourceLowerBoundConstraint: {}
#  ResourceUpperBoundConstraint: {}
#  cost: {}
#  supply: {}
#  demand: {}
#
#- type: blacksmith
#  ResourceLowerBoundConstraint: {}
#  ResourceUpperBoundConstraint: {}
#  cost: {}
#  supply: {}
#  demand: {}
#
#- type: market
#  ResourceLowerBoundConstraint: {}
#  ResourceUpperBoundConstraint: {}
#  cost: {}
#  supply: {}
#  demand: {}
#
#- type: pasture
#  ResourceLowerBoundConstraint: {}
#  ResourceUpperBoundConstraint: {}
#  cost: {}
#  supply: {}
#  demand: {}
#
#- type: castle
#  ResourceLowerBoundConstraint: {}
#  ResourceUpperBoundConstraint: {}
#  cost: {}
#  supply: {}
#  demand: {}
#
#- type: barracks
#  ResourceLowerBoundConstraint: {}
#  ResourceUpperBoundConstraint: {}
#  cost: {}
#  supply: {}
#  demand: {}
#
#- type: vineyard
#  ResourceLowerBoundConstraint: {}
#  ResourceUpperBoundConstraint: {}
#  cost: {}
#  supply: {}
#  demand: {}